### ISSUE TITLE
Commands cleanup

### ISSUE THREAD

**Issue by L4444** [carinus-mud/carinus#28]
When new players type "commands" they are overwhelmed by over 200 commands.

I suggest we clean this up, me and xander have spoke about this and moved some of the mprog commands to a higher "level" e.g. mea,mpe

As I write this Xander is going through the commands and moving some of the useless ones.

What I propose is the "commands" keyword to list all the commands and put their aliases with them. I'm thinking something along the lines of:

score (score,stats)         kill (kill, attack)      emote ("emote", ",")

My goal for this issue is to reduce the commands down to a short list that is not overwhelming.

**Comment by L4444** [comment]
I am "You" and "someone" is Xander, this is what we talked about while in the mud.

You say 'I believe firmly that we should focus on the start'
You say 'and THEN work our way back'
You ask, 'Do you get what I mean?'
You say 'Focus on the start of the new player experience.'
Someone nods solemnly.
You say 'There is a lot of work to do.'
Someone says 'just one of the many things to change'
Someone says 'yeah and I'll probably do like 90% of it lol'
You say 'I'm gonna merge my very minor changes to master'
Someone says 'just make one large issue at a time with things you see that need fixing, like ubraxis 
is doing'
Someone says 'i'll get to them all'
Someone says 'what you and mr hydra don't get to anyway'
You say 'Ok, I've added command cleanup to the issue list.'
Someone nods solemnly.
Someone says 'i'd just have a coded output and check if you are in a clan or council to output the 
rest of the commands under the label "council commands" or "guild commands"'
You say 'in an ideal world commands would be like 20 commands tops'
Someone says 'well...'
Someone says 'you have to think.. it's putting in all directions as commands as well'
You say 'command (aliases) what it does, usage'
You say 'e.g.'
Someone says 'so if you take out the BS like that, the council/clan specific ones, and consolodate 
all the aliases... there are like 20'
Someone says 'we can actually have "quit" do a string of "save" "savearea" then "quit"'
You say 'emote ("emote",",") make your character perform a custom action e.g. emote jumps for joy = 
John jumps for joy.'
You ask, 'Why do players need to "save"?'

**Comment by L4444** [comment]
Some more things.... my thoughts
Languages -> score
gold -> inventory
wtf does "traffic" do?
is beckon a social?
"rap" should be replaced with "knock"
"leave" you cannot find an exit here? but there are 2 exits? why is there enter and leave? for vehicles?
"brandish" should be moved into wield.

**Comment by joeyfogas** [comment]
commands list is done. please set all suggestions as new issues :)
