### ISSUE TITLE
remove the indoors flag

### ISSUE THREAD

**Issue by L4444** [carinus-mud/carinus#33]
According to room.help
INDOORS       | Room is indoors - MUST also use sectortype 0

If the indoors flag must be used with sectortype 0, then surely any checks for the indoors flag can be replaced with checking the room's sector for "inside".

Geez this is a spicy codebase.

**Comment by joeyfogas** [comment]
actually, not necessarily.  the help files were from original smaug (mostly) and are invalid.  You can have an indoors in a Forrest (tent, cave) or even in a field (covered wagon).  The indoors flag is needed.
